// Generates lib/schemas.generated.ts (zod) from the backend's Pydantic JSON Schemas.
// Reads the same EXPORTED_MODELS that GET /api/schema/{model} serves, via the backend venv,
// so the backend server does not need to be running. Run: npm run gen:schemas
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const backend = join(root, "..", "backend");
const python = [
  join(backend, ".venv", "Scripts", "python.exe"),
  join(backend, ".venv", "bin", "python"),
].find(existsSync);
if (!python) throw new Error("backend/.venv not found; create the backend venv first");

const dump = `
import json
from app.api.schema import EXPORTED_MODELS
print(json.dumps({name: cls.model_json_schema() for name, cls in EXPORTED_MODELS.items()}))
`;
const schemas = JSON.parse(execFileSync(python, ["-c", dump], { cwd: backend, encoding: "utf8" }));

// json-schema-to-zod does not follow $ref: inline Pydantic's "#/$defs/X" references.
function inlineRefs(node, defs) {
  if (Array.isArray(node)) return node.map((n) => inlineRefs(n, defs));
  if (node === null || typeof node !== "object") return node;
  const { $ref, ...rest } = node;
  delete rest.$defs;
  const out = Object.fromEntries(Object.entries(rest).map(([k, v]) => [k, inlineRefs(v, defs)]));
  if ($ref) return { ...inlineRefs(defs[$ref.replace("#/$defs/", "")], defs), ...out };
  return out;
}

const parts = [
  "// GENERATED by scripts/gen-schemas.mjs from the backend Pydantic models. Do not edit.",
  'import { z } from "zod";',
];
for (const [name, schema] of Object.entries(schemas).sort()) {
  const body = jsonSchemaToZod(inlineRefs(schema, schema.$defs ?? {}), { name: `${name}Schema`, module: "none", depth: 4 });
  parts.push(`export ${body}`, `export type ${name} = z.infer<typeof ${name}Schema>;`);
}
writeFileSync(join(root, "lib", "schemas.generated.ts"), parts.join("\n\n") + "\n");
console.log(`wrote lib/schemas.generated.ts (${Object.keys(schemas).length} schemas)`);
